# Generated by Django 4.2.6 on 2023-12-12 12:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.DurationField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.timedelta(seconds=120))], verbose_name='Длительность выполнения'),
        ),
    ]
